/* 2022-09-02 */
/* JGM_DBA 계정 */

/* 테이블 생성 */

/*
테이블 생성 후 별도의 권한 없이도 입력은 가능하지만, 할당받은 공간이 없기 때문에 실제 입력은 불가능.

CREATE TABLE 테이블명(컬럼이름1 데이터타입, 컬럼이름2 데이터타입, ......);

*/
CREATE TABLE SCORES(
    STUNAME NVARCHAR2(5),
    JAVASCORE NUMBER,
    ORACLESCORE NUMBER,
    HTMLSCORE NUMBER
);

DESC SCORES;
/* 데이터 입력 */
/*
INSERT INTO 테이블명(컬럼명 1, 컬럼명 2, ....)
VALUES( 컬럼명 1에 입력할 값, 컬럼명 2에 입력할 값, ....);
*/

INSERT INTO SCORES(STUNAME, JAVASCORE, ORACLESCORE, HTMLSCORE)
VALUES('정균민', 80, 85, 90 );

SELECT * FROM SCORES
WHERE STUNAME = '정균민'
;

SELECT * FROM SCORES;

INSERT INTO SCORES (JAVASCORE, STUNAME, ORACLESCORE, HTMLSCORE)
VALUES(100, '박민서', 100, 100 );


INSERT INTO SCORES(STUNAME, JAVASCORE, HTMLSCORE)
VALUES('정균민', 80, 90 );

INSERT INTO SCORES
VALUES('정균민', 80, 90 );

/* 학생 정보(STUINFO) 테이블 */
/* 학생이름, 학교이름, 전화번호 */

CREATE TABLE STUINFO(
    STUNAME NVARCHAR2(5),
    SCHNAME NVARCHAR2(10),
    TEL     NVARCHAR2(13),
    BIRTHDATE NVARCHAR2(7)
);

INSERT INTO STUINFO VALUES('정균민', '인하대학교', '010-5362-8640', '19960812');

SELECT * FROM STUINFO;

-- DELETE FROM STUINFO WHERE STUNAME = '정균민'; 
ALTER TABLE STUINFO MODIFY BIRTHDATE VARCHAR2(10);


INSERT INTO STUINFO
VALUES('정균민', '인하대학교', '010-5362-8640', '960812');

DELETE FROM STUINFO WHERE BIRTHDATE ='960812';


/*전화번호부(PHONEBOOK) 
이름, 전화번호, 생년월일, 임시

숫자형, 문자형, 날짜형

*/

CREATE TABLE TEST_TBL01(
    TEST_COL1 CHAR(2),
    TEST_COL2 NCHAR(2)
);

INSERT INTO TEST_TBL01(TEST_COL1) VALUES('가');
INSERT INTO TEST_TBL01(TEST_COL2) VALUES('나');


SELECT * FROM TEST_TBL01;

DELETE FROM TEST_TBL01 WHERE TEST_COL2 = '나';

/*
문자형:
        [고정형]
        CHAR
        NCHAR(5)       >> 5글자 :: 'A' ===> [A][][][][]

        [가변형]
        VARCHAR
        NVARCHAR(5)    >> 5글자 :: 'A' ===> [A]
        
TBL01
정,균,민, , ,0,1,0,-.......
임,철,  , , ,0,1,0,-.......

TBL02
정,균,민, , ,0,1,0,-.......
임,철,  , , ,0,1,0,-....... 

*/

CREATE TABLE TESTTBL02(
    TESTNUM1 NUMBER,
    TESTNUM2 NUMBER(3),
    TESTNUM3 NUMBER(3, 2)
);


INSERT INTO TESTTBL02(TESTNUM2) VALUES(1);
-- 1 행 이(가) 삽입되었습니다.
INSERT INTO TESTTBL02(TESTNUM2) VALUES(11);
-- 1 행 이(가) 삽입되었습니다.
INSERT INTO TESTTBL02(TESTNUM2) VALUES(111);
-- 1 행 이(가) 삽입되었습니다.
INSERT INTO TESTTBL02(TESTNUM2) VALUES(1111);
-- ORA-01438: 이 열에 대해 지정된 전체 자릿수보다 큰 값이 허용됩니다.

INSERT INTO TESTTBL02(TESTNUM2) VALUES(1.11);
-- 1 행 이(가) 삽입되었습니다.
INSERT INTO TESTTBL02(TESTNUM2) VALUES(2.222);
-- 1 행 이(가) 삽입되었습니다.

INSERT INTO TESTTBL02(TESTNUM2) VALUES(333.33);
SELECT *FROM TESTTBL02;

INSERT INTO TESTTBL02(TESTNUM1) VALUES(1234.1234);
INSERT INTO TESTTBL02(TESTNUM1) VALUES(12345.12345);


INSERT INTO TESTTBL02(TESTNUM3) VALUES(1.1);
INSERT INTO TESTTBL02(TESTNUM3) VALUES(1.12);
INSERT INTO TESTTBL02(TESTNUM3) VALUES(1.123);
INSERT INTO TESTTBL02(TESTNUM3) VALUES(1.1234);

DELETE FROM TESTTBL02 WHERE TESTNUM1 = 1234.1234;

INSERT INTO TESTTBL02(TESTNUM3) VALUES(21.1);
INSERT INTO TESTTBL02(TESTNUM3) VALUES(21.12);
INSERT INTO TESTTBL02(TESTNUM3) VALUES(21.123);
INSERT INTO TESTTBL02(TESTNUM3) VALUES(21.1234);

/* 날짜형 (년월일 시분초)*/
CREATE TABLE TESTTBL03(
    TESTDATE DATE
);


INSERT INTO TESTTBL03 VALUES('2022-09-02');
--  1 행 이(가) 삽입되었습니다.
INSERT INTO TESTTBL03 VALUES('2022/09/03');
--  1 행 이(가) 삽입되었습니다.
INSERT INTO TESTTBL03 VALUES('2022AA');

-- INSERT INTO TESTTBL03 VALUES('2022/09/02 20:58:30');
INSERT INTO TESTTBL03 VALUES(TO_DATE('2022/09/02 20:58:30', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TESTTBL03 VALUES(TO_DATE('2022/09/02', 'YYYY-MM-DD'));
INSERT INTO TESTTBL03 VALUES(SYSDATE);
SELECT *FROM TESTTBL03;
ROLLBACK;


INSERT INTO TESTTBL03 VALUES(SYSDATE - 1);

INSERT INTO TESTTBL03 VALUES(SYSDATE - 10);

INSERT INTO TESTTBL03 VALUES(SYSDATE - (1 / 24));

INSERT INTO TESTTBL03 VALUES(SYSDATE - (1 / 24));


SELECT *FROM TESTTBL03;

/*
전화번호부(PHONEBOOK)
이름, 전화번호, 생년월일
숫자형, 문자형, 날짜형
*/

CREATE TABLE PHONEBOOK(
    PNAME NVARCHAR2(5),
    PHONENUM NVARCHAR2(13),
    PBIRTH DATE
);

-- 날짜 타입의 데이터를 TOCHARACTER로 문자형으로 바꿀 수 있다.