/* 22-09-13 */
SELECT * FROM EMP;
SELECT * FROM DEPT;

/* JOIN : 두개 이상의 테이블을 연결하여 데이터를 조회 */

SELECT *
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO;

SELECT *
FROM EMP INNER JOIN DEPT
ON EMP.DEPTNO = DEPT.DEPTNO;

/* 부서명이 'REASEARCH' 인 직원 정보 조회 */

SELECT *
FROM DEPT, EMP
WHERE EMP.DEPTNO = DEPT.DEPTNO AND DEPT.DNAME = 'RESEARCH';

SELECT *
FROM EMP INNER JOIN DEPT ON DEPT.DEPTNO = EMP.DEPTNO
WHERE DEPT.DNAME = 'RESEARCH';

SELECT EMP.*, DEPT.LOC
FROM EMP INNER JOIN DEPT ON DEPT.DNAME = 'RESEARCH'
WHERE DEPT.DEPTNO = EMP.DEPTNO;

-- 직원이름이 'MARRTIN'인 직원의 직원 번호, 직원이름, 부서명, 부서위치
SELECT EMP.EMPNO, EMP.ENAME, DEPT.DNAME, DEPT.LOC
FROM EMP, DEPT
WHERE (EMP.DEPTNO = DEPT.DEPTNO) AND EMP.ENAME = 'MARTIN';

-- 부서위치가 'NEW YORK'인 직원들의 이름, 직무 조회
SELECT EMP.ENAME, EMP.JOB
FROM EMP, DEPT
WHERE (EMP.DEPTNO = DEPT.DEPTNO) AND DEPT.LOC = 'NEW YORK';

SELECT EMP.ENAME, EMP.JOB
FROM EMP INNER JOIN DEPT ON DEPT.LOC = 'NEW YORK'
WHERE (EMP.DEPTNO = DEPT.DEPTNO);

-- COMM이 있는 직원의 이름, 부서명 조회
SELECT EMP.ENAME, DEPT.DNAME
FROM EMP, DEPT
WHERE (EMP.DEPTNO = DEPT.DEPTNO) AND EMP.COMM IS NOT NULL;

-- OUTER JOIN 겹치지 않는 부분만 보여줌.

-- 각 부서별 인원수

SELECT EMP.DEPTNO, DEPT.DNAME, COUNT(*)
FROM EMP, DEPT
WHERE (EMP.DEPTNO = DEPT.DEPTNO)
GROUP BY EMP.DEPTNO, DEPT.DNAME;


SELECT EMP.DEPTNO, DEPT.DNAME
FROM DEPT
LEFT OUTER JOIN ( SELECT EMP.DEPTNO, COUNT(*) AS DEPTCOUNT
                  FROM EMP
                  GROUP BY EMP.DEPTNO ) EMP
ON DEPT.DEPTNO = EMP.DEPTNO;

-- 부서위치(DEPT.LOC)가 'NEW YORK'인 직원들의 이름(EMP.ENAME), 직무(ENAME.JOB) 조회
-- JOIN 없이 사용

SELECT EMP.ENAME, EMP.JOB
FROM EMP
WHERE EMP.DEPTNO = (SELECT DEPTNO
                    FROM DEPT
                    WHERE LOC = 'NEW YORK');

SELECT DEPTNO
FROM DEPT
WHERE LOC = 'NEW YORK'; -- 결과: 부서번호 10번

SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO = 10;

SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM DEPT);

-- ORA-01722: 수치가 부적합합니다
SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO IN (SELECT DNAME
                FROM DEPT);

-- ORA-00913: 값의 수가 너무 많습니다
SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO, DNAME
                FROM DEPT
                WHERE LOC = 'NEW YORK');
                
-- 'KING'과 같은 부서에서 근무하는 직원들의 이름, 직무 조회
SELECT ENAME, JOB
FROM EMP
WHERE DEPTNO = (SELECT DEPTNO
                FROM EMP
                WHERE ENAME = 'KING');
-- 급여가 1500인 직원과 같은 직무의 직원들의 이름 조회
SELECT ENAME
FROM EMP
WHERE JOB = (SELECT JOB
             FROM EMP
             WHERE SAL = 1500);

SELECT JOB, COUNT(*)
FROM EMP
WHERE JOB = (SELECT JOB
             FROM EMP
             WHERE SAL = 1500)
GROUP BY JOB;

-- 급여가 1500인 직원과 다른 직무의 직원들의 이름 조회

SELECT ENAME
FROM EMP
WHERE JOB NOT IN (SELECT JOB
             FROM EMP
             WHERE SAL = 1500);

SELECT E.ENAME
FROM EMP E
WHERE JOB != 'SALESMAN';

/* 급여가 1000 미만인 직원 근무하는 부서의 직원이름, 급여, 부서번호 조회 */
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
                 FROM EMP
                 WHERE SAL <= 1000)
ORDER BY DEPTNO DESC, SAL DESC;

/* 급여가 1000 미만인 직원 근무하는 부서의 부서번호 및 부서별 인원수 조회 */
SELECT DEPTNO, COUNT(*)
FROM EMP
WHERE DEPTNO IN (SELECT DEPTNO
                FROM EMP
                WHERE SAL <= 1000)
GROUP BY DEPTNO;

/* 평균 급여가 2000이상인 부서의 부서이름, 위치 조회 */
SELECT DNAME, LOC
FROM DEPT 
WHERE DEPTNO IN (SELECT DEPTNO
                   FROM EMP
                   GROUP BY DEPTNO
                   HAVING AVG(SAL) >= 2000);

SELECT DEPTNO, AVG(SAL)
FROM EMP
GROUP BY DEPTNO
HAVING AVG(SAL) >= 2000;
/* 급여를 3000이상 받는 직원과 같은 부서에서 근무하는 직원이름, 급여, 부서이름 조회 */
SELECT E.ENAME, E.SAL, D.DNAME
FROM EMP E, DEPT D
WHERE (E.DEPTNO = D.DEPTNO) AND  E.DEPTNO IN (SELECT DEPTNO
                                              FROM EMP
                                              WHERE SAL >= 3000);

Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1234','제로사이다',2000,123,'음료');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0012','샌드위치',2300,10,'식품');
Insert into 
(PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P3030','행복복권',5000,100,'복권');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P8001','ATmega128',20604,5,'MCU');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P5001','대형우산',40000,10,'우산');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1414','아이폰 14 PRO MAX',2500000,1000,'휴대폰');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P7006','노트북가방',30000,5,'가방');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P8801','RTX 3080 Ti',1434960,1,'GPU');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1052','독립일기',12000,30,'웹툰');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1053','내남편과결혼해줘',15000,30,'웹툰');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1054','외모지상주의',15000,40,'웹툰');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P5959','오구오구',59595959,59,'59');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P9002','복근 롤러',50000,20,'운동기구');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P9999','송도더샵퍼스트월드(주상복합)',1200000000,1,'매매');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0000','무형검',0,0,'LEGENDARY');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0001','테스트상품1',1,1,'테스트');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1003','제로 후르츠 젤리',1500,1,'젤리');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1004','아임리얼 딸기',3300,1,'음료');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0831','BTS',500000,7,'아이돌');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1232','초코파이',10,1000,'과자');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1233','빅파이',4950,50,'과자');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0710','민트맛파인애플',12000,10,'과일');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1005','쿨피스',600,12,'음료');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P8282','아이폰14PRO MAX',1500000,1,'전자기기');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P8202','김민지',20,1,'인간');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0711','조빵매',1200,1,'장난감');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1001','아이스티레몬',1200,20,'음료');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1002','아이스티복숭아',1200,30,'음료');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P2301','모두의 아두이노',15000,5,'책');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1014','오감자',2500,40,'과자');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0921','상품',21,1,'테스트');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1015','스윙칩',2000,20,'과자');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P1016','빈츠',1500,23,'과자');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P4352','일보치킨',8000,10,'식품');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P6034','일보탄산수',1000,30,'음료');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0123','칙촉',1,1,'과자');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P9318','일보피자',9000,20,'식품');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0201','먹자마자 효과좋은 변비약',10,25,'약품');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0200','서율',10000000,1,'환혼');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0010','슬리퍼',3000,1,'신발');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0011','코카콜라제로',1500,5,'탄산음료');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0009','아메리카노',1,1,'테스트');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0904','한진민',10,100,'과자');
Insert into PRODUCT (PDCODE,PDNAME,PDPRICE,PDAMOUNT,PDTYPE) values ('P0905','한진민1',10,100,'장난감');

SELECT * FROM PRODUCT;
commit;







































